version: '3'

services:
  mysql_db:
    image: mysql:8.0.1
    restart: always
    environment:
      MYSQL_DATABASE: ts_employees
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - my-datavolume-ext:/var/lib/mysql
    ports:
      - "3306:3306"


  bot:
    depends_on:
      - mysql_db
    build: 
      context: ./app
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: $DATABASE_HOST
      DATABASE_NAME: $DATABASE_NAME
      DATABASE_USER: $DATABASE_USER
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      GMAIL_EMAIL: $GMAIL_EMAIL
      GMAIL_PASSWORD: $GMAIL_PASSWORD
      TELEGRAM_TOKEN: $TELEGRAM_TOKEN
    restart: always

volumes:   
  my-datavolume-ext:
